[package]
name = "cairo_cmtat"
version = "1.0.0"
edition = "2023_11"
description = "Comprehensive CMTAT implementation in Cairo for Starknet"
license = "MPL-2.0"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.25.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
exit_first = true
